### PR TITLE
Upgrades

### LINKED ISSUE #1: Testing on windows (anaconda installation)
Hi 

I just tried this in my Anaconda distribution on windows. 

I got the following error. I don't know if you expected it to work on windows, but I got the following ERROR. Maybe it is useful.

``` cmd
C:\Users\mel\Documents\GitHub\xonsh_kernel>ipython qtconsole --kernel=xonsh_kernel
---------------------------------------------------------------------------
TIMEOUT                                   Traceback (most recent call last)
C:\Users\mel\Anaconda3\lib\site-packages\metakernel-0.9.0-py3.4.egg\metakernel\pexpect.py in expect_loop(self=<metakernel.pexpect.Ex
pecter object>, timeout=-0.0007159709930419922)
    222                 if (timeout is not None) and (timeout < 0):
--> 223                     return self.timeout()
        self.timeout = <bound method Expecter.timeout of <metakernel.pexpect.Expecter object at 0x00000000048C4358>>
    224                 # Still have time left, so read more data

C:\Users\mel\Anaconda3\lib\site-packages\metakernel-0.9.0-py3.4.egg\metakernel\pexpect.py in timeout(self=<metakernel.pexpect.Expect
er object>, err=None)
    196                 msg = str(err) + '\n' + msg
--> 197             raise TIMEOUT(msg)
        global TIMEOUT = <class 'metakernel.pexpect.TIMEOUT'>
        msg = "<metakernel.pexpect.spawnu object at 0x00000000048C4278>\nversion: 3.3\ncommand: C:\\Users\\mel\\Anaconda3\\Scripts\\
xonsh.EXE\nargs: ['C:\\\\Users\\\\mel\\\\Anaconda3\\\\Scripts\\\\xonsh.EXE']\nsearcher: None\nbuffer (last 100 chars): ''\nbefore (l
ast 100 chars): ''\nafter: <class 'metakernel.pexpect.TIMEOUT'>\nmatch: None\nmatch_index: None\nexitstatus: None\nflag_eof: False\n
pid: 11372\nchild_fd: 7\nclosed: False\ntimeout: 30\ndelimiter: <class 'metakernel.pexpect.EOF'>\nlogfile: None\nlogfile_read: None\
nlogfile_send: None\nmaxread: 2000\nignorecase: False\nsearchwindowsize: None\ndelaybeforesend: 0.05\ndelayafterclose: 0.1\ndelayaft
erterminate: 0.1"
    198

TIMEOUT: <metakernel.pexpect.spawnu object at 0x00000000048C4278>
version: 3.3
command: C:\Users\mel\Anaconda3\Scripts\xonsh.EXE
args: ['C:\\Users\\mel\\Anaconda3\\Scripts\\xonsh.EXE']
searcher: None
buffer (last 100 chars): ''
before (last 100 chars): ''
after: <class 'metakernel.pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 11372
child_fd: 7
closed: False
timeout: 30
delimiter: <class 'metakernel.pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
```

### PR DESCRIPTION
**Pull request by blink1073**
Relies on https://github.com/scopatz/xonsh/pull/634.

Fixes #1.

### CODE REVIEW

**Comment by scopatz** [comment]
Does this need a xonsh release in order to work?  I am happy to do one if that is the case.

**Comment by blink1073** [comment]
Yes, this relies on a merge of that PR and a release.  I've confirmed this works on Windows and OSX.

**Comment by scopatz** [comment]
Ok cool. Do you want push rights to xonsh in order to potentially speed this along?

**Comment by blink1073** [comment]
I'll stick with the standard PR route, thanks.  I've got my fingers in enough pies already :).

**Comment by scopatz** [comment]
OK, just thought I'd offer!

**Comment by blink1073** [comment]
Success, thanks @scopatz!

**Pull request merged**
